### ISSUE TITLE
NullPointerException for RemoteResourceIndex

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#193]
We've configured a `RemoteResourceIndex` as follows (in `CDXCollection.xml`):

    <property name="resourceIndex">
        <bean class="org.archive.wayback.resourceindex.RemoteResourceIndex">
            <property name="searchUrlBase" value="http://___.bl.uk:8080/wayback/xmlquery" />
        </bean>
    </property>

This correctly returns results (i.e. the calendar is correctly displayed when searching) but when trying to view a resource, a `NullPointerException` is thrown:

    WARNING: Runtime Error
      java.lang.NullPointerException
        at org.archive.wayback.replay.DateRedirectingClosestResultSelector.getClosest(DateRedirectingClosestResultSelector.java:40)
        at org.archive.wayback.replay.SelectorReplayDispatcher.getClosest(SelectorReplayDispatcher.java:71)
        at org.archive.wayback.webapp.AccessPoint.handleReplay(AccessPoint.java:677)
        at org.archive.wayback.webapp.AccessPoint.handleRequest(AccessPoint.java:311)

This seems to be correct as the `closest` result in the `CaptureSearchResults` never gets set.

**Comment by PsypherPunk** [comment]
Tried to fix this in #194—the `LocalResourceIndex` uses a `ClosestResultTrackingFilter` which annotates the results and marks the closest. I've tried to duplicate that process here.

**Comment by anjackson** [comment]
Okay to close this?

**Comment by PsypherPunk** [comment]
Yep, fixed in #194.
