### ISSUE TITLE
Indexing of WARCs created by Squidwarc does not work: Unexpected character 57(Expecting d)

### ISSUE THREAD

**Issue by peterk** [iipc/openwayback#379]
I am trying to use openwayback to index/play back WARC files created by Squidwarc but get the following error when indexing them. Not sure if this is an error with Squidwarc or with openwayback so cross referencing the issues. I have attached an example WARC file to the corresponding [issue for Squidwarc](https://github.com/N0taN3rd/Squidwarc/issues/32).

Using version 2.4.0-SNAPSHOT of openwayback running in a Docker container.

```
Oct 21, 2018 12:08:23 PM org.archive.io.ArchiveReader$ArchiveRecordIterator hasNext
WARNING: Trying skip of failed record cleanup of {reader-identifier=/data/files1/instagram.com!visit_berlin-10-21-2018_1540123477677.warc, absolute-offset=0, WARC-Filename=instagram.com!visit_berlin-10-21-2018_1540123477677.warc, WARC-Date=2018-10-21T12:04:37Z, Content-Length=379, WARC-Record-ID=<urn:uuid:7b817fe0-d529-11e8-8ec6-391ee1fffcc8>, WARC-Type=warcinfo, Content-Type=application/warc-fields}: Unexpected character 57(Expecting d)
java.io.IOException: Unexpected character 57(Expecting d)
	at org.archive.io.warc.WARCReader.readExpectedChar(WARCReader.java:80)
	at org.archive.io.warc.WARCReader.gotoEOR(WARCReader.java:70)
	at org.archive.io.ArchiveReader.cleanupCurrentRecord(ArchiveReader.java:176)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.hasNext(ArchiveReader.java:449)
	at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.hasNext(ArchiveReaderCloseableIterator.java:37)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.resourcestore.indexer.IndexWorker.main(IndexWorker.java:216)
```

**Comment by peterk** [comment]
This was due to an issue in a component in squidwarc / node-ward (https://github.com/N0taN3rd/Squidwarc/issues/32). Now fixed so closing this issue.
